### ISSUE TITLE
어떤 CSS Style 기법을 사용할 것인가?

### ISSUE THREAD

**Issue by tubeletter** [tubeletter/chakra-ui-clone#1]
- [ ] SCSS
- [ ] CSS
- [x] React Styled Component
- [x] React CSS Module

**Comment by GaYunKimm** [comment]
-[ ] StyleX - CSS In JS

**Comment by RunaUXLabs** [comment]
클론 프로젝트 자체가 리액트로 진행된다면   StyleX - CSS In JS, Styled Component, CSS Module로 가야 고생을 안할 것 같긴 합니다. 지금 해당 키워드들 다 검색해서 보니까 리액트에서 일반 css를 간혹 쓰기는하나 다들 비추하시네요.
저는 StyleX - CSS In JS, Styled Component, CSS Module셋 중 하나이고, 확정되면 그것위주로 공부하겠습니다.

**Comment by yhyunmin** [comment]
- [ ] Tailwind CSS
기회가된다면 이참에 테일윈드를 만져보고싶네요... !

**Comment by rebehayan** [comment]
stylex 제외하고 체험하고싶어용~~

**Comment by tubeletter** [comment]
[팀/사용 기술 스택]
A팀(CSS-in-JS): Styled-Component
팀원: @리베하얀 @루나 @뽀잉맨 @웃음

B팀(Non CSS-in-JS): SASS Module
팀원: @튜브 @예감 @울태
